# Generated by Django 4.0.8 on 2022-11-03 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('method', models.TextField()),
                ('message', models.TextField()),
                ('frontendId', models.TextField(default='-1')),
            ],
        ),
        migrations.CreateModel(
            name='TutorGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserChangeLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('message', models.TextField()),
                ('frontendId', models.TextField(default='-1')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('matriculation_number', models.TextField()),
                ('tutor_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='generic_app.tutorgroup')),
            ],
        ),
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('exercise', models.TextField()),
                ('points', models.FloatField()),
                ('max_points', models.FloatField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generic_app.student')),
            ],
        ),
    ]
