# Generated by Django 4.0.8 on 2022-11-03 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupStructureUpload',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('student_file', models.FileField(upload_to='')),
                ('tutor_file', models.FileField(upload_to='')),
                ('group_file', models.FileField(upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='points',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='points',
            name='max_points',
        ),
        migrations.RemoveField(
            model_name='points',
            name='points',
        ),
        migrations.RemoveField(
            model_name='points',
            name='student',
        ),
    ]
