# Generated by Django 4.0.8 on 2022-11-04 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic_app', '0002_groupstructureupload_remove_points_exercise_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseUpload',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
