# Generated by Django 4.0.8 on 2022-11-04 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic_app', '0004_studentreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='tutor_group',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TutorGroup',
        ),
    ]
